cuda
Traceback (most recent call last):
  File "/home/baebro/landmark_extraction/model/train.py", line 91, in <module>
    pos_emb = model(pos)
  File "/home/baebro/anaconda3/envs/mp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/baebro/anaconda3/envs/mp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/baebro/landmark_extraction/model/model.py", line 20, in forward
    x, _ = self.lstm1(x)
  File "/home/baebro/anaconda3/envs/mp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/baebro/anaconda3/envs/mp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/baebro/anaconda3/envs/mp/lib/python3.10/site-packages/torch/nn/modules/rnn.py", line 1123, in forward
    result = _VF.lstm(
RuntimeError: Expected sequence length to be larger than 0 in RNN
